# Project information

site_name: Halloweenie Roast
site_description: Event page for the 2019 Haines Family Halloweenie Roast
site_author: Josh Haines
site_url: http://weenie-roast.com

# Navigation
nav:
    - index.md
    - food.md
    - drinks.md
    - activities.md
    - location.md
    - rsvp.md
    - history.md

# Themes
theme:
  name: 'material'
  custom_dir: 'weenietheme'
  logo: 'img/fire.png'
  palette:
    primary: 'Brown'
    accent: 'Orange'

  

extra:
    feature:
        tabs: false

# Extensions
markdown_extensions:
    - admonition:
    - pymdownx.tilde:

# Custom CSS
extra_css:
    - 'stylesheets/extra.css'

# Copyright String
copyright: "Josh Haines - 2019"

# Author String
site_author: "Josh Haines"

# update serving address and port
dev_addr: '0.0.0.0:8180'